version: '3.4'

services:
  boilerplate.host:
    image: ${PRIVATE_REGISTRY}/boilerplatehost
    env_file:
      - .env
    build:
      context: ./app
      dockerfile: src/Boilerplate.Host/Dockerfile
