name: BoilerPlate Build
trigger:
- master

pool:
  vmImage: 'Ubuntu 16.04'

variables:
  buildConfiguration: 'Release'
  Major: '1'
  Minor: '0'
  Patch: '0'
  node_version: '10'
  dockerId: CGBoilerplateCR 
  tagName: latest
  repository: $(dockerId).azurecr.io

steps:
- script: |
    docker-compose build

- task: CopyFiles@2
  displayName: 'Copy ARM templates'
  inputs:
    SourceFolder: infra
    Contents: '*.json'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- script: |
    docker login -u $(dockerId) -p $(dockerPassword) $(repository)
    docker-compose push
  displayName: 'Pushing Docker images'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'